server:
  port: 8080

spring:
  profiles:
    active: test

  #### datasource
  datasource:
    driver-class-name: ${driver-class-name}
    url: ${url}
    username: ${username}
    password: ${password}

  #### JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql

#### logging
logging:
  level:
    root: ${logging}
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

#### file upload path
upload.path: ${upload.path}