server:
  port: 8080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
      uri: "mongodb://localhost:27017/test"
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 10MB
  mongodb:
    embedded:
      version: 3.2.3